set(capo_headers
  include/capo/capo.hpp
  include/capo/channels.hpp
  include/capo/clip.hpp
  include/capo/compression.hpp
  include/capo/device.hpp
  include/capo/duration.hpp
  include/capo/error_handler.hpp
  include/capo/frame_index.hpp
  include/capo/pcm.hpp
  include/capo/orientation.hpp
  include/capo/sample.hpp
  include/capo/sound_source.hpp
  include/capo/state.hpp
  include/capo/stream_source.hpp
  include/capo/stream.hpp
  include/capo/vec3.hpp
)
